config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  resources :home, only: [:index], controller: :home
  resources :default, only: [:index], controller: :default
  resources :courses, only: [:index, :show], controller: :courses
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/slug.rb
# frozen_string_literal: true

module Slug
  extend ActiveSupport::Concern
  included do
    # Callbacks
    before_validation :generate_slug, on: :create, uniqueness: true

    # Call slug instead of ID
    def to_param
      slug
    end

    # String Generator
    def generate_slug(size = 8)
      charset = [("a".."z"), ("A".."Z"), (0..9)].map(&:to_a).flatten
      string = (0...size).map { charset[rand(charset.size)] }.join
      self.slug = string
    end
  end
end

app/models/courses.rb
# frozen_string_literal: true

class Courses < ApplicationRecord
  # Table name
  self.table_name = "magestil_courses"

  # Concerns
  include Slug
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  # /courses
  def index
  end

  # /courses/slug
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/default_controller.rb
# frozen_string_literal: true

class DefaultController < ApplicationController
  # /default
  def index
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  layout "application_landing"
  # /
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Application configuration
  def application_configuration
    Rails.configuration.application_configuration
  end

  def image_set_tag(source, srcset = {}, options = {})
    srcset = srcset.map { |src, size| "#{path_to_image(src)} #{size}" }.join(', ')
    image_tag(source, options.merge(srcset: srcset))
  end
end

app/views/courses/_section.html.haml
%h3 #{params[:title]}
.trix.white-100-bg
  %div Nulla vitae elit libero, a pharetra augue. Vestibulum id ligula porta felis euismod semper. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.

  %div Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus.

  %div Curabitur blandit tempus porttitor. Nulla vitae elit libero, a pharetra augue. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Curabitur blandit tempus porttitor.

  %ul
    %li Quam Euismod Ornare Pellentesque Magna
    %li Cras Ullamcorper
    %li Ligula Fusce Commodo

  %div Curabitur blandit tempus porttitor. Nulla vitae elit libero, a pharetra augue. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Curabitur blandit tempus porttitor.

  %ol
    %li Quam Euismod Ornare Pellentesque Magna
    %li Cras Ullamcorper
    %li Ligula Fusce Commodo

  %div Nullam quis risus eget urna mollis ornare vel eu leo. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Cras mattis consectetur purus sit amet fermentum. Donec ullamcorper nulla non metus auctor fringilla.

  %ul
    %li Conceber e maquetizar objetos gráficos bidimensionais e tridimensionais utilizando meios eletrónicos e manuais;
    %li Obter imagens e textos por processos eletrónicos;
    %li Criar imagens, gráficos, ilustrações e animações, utilizando meios manuais e informáticos, para determinado fim e/ou tipo de impressão;
    %li Efetuar o tratamento de textos relativamente à sua forma e conteúdo, utilizando programas informáticos específicos;
    %li Efetuar o tratamento de imagens, relativamente à sua cor e forma, utilizando programas informáticos específicos;
    %li Compor a estrutura das páginas, utilizando programas de informática específicos;
    %li Executar provas de baixa e alta resolução e heliográficas (ozalides), utilizando meios eletrónicos, a fim de verificar a sua conformidade com os objetivos pretendidos;
    %li Efetuar o registo da composição gráfica, em película e em chapa, com vista à sua posterior impressão, utilizando meios eletrónicos;
    %li Proceder à calibração dos equipamentos de forma a obter a qualidade pretendida na reprodução dos trabalhos gráficos;
    %li Efetuar o tratamento de textos e de imagens, compor e conceber as páginas para publicação “online” ou para apresentações “offline”.
    %li Conceber e maquetizar objetos gráficos bidimensionais e tridimensionais utilizando meios eletrónicos e manuais;
    %li Obter imagens e textos por processos eletrónicos;
    %li Criar imagens, gráficos, ilustrações e animações, utilizando meios manuais e informáticos, para determinado fim e/ou tipo de impressão;
    %li Efetuar o tratamento de textos relativamente à sua forma e conteúdo, utilizando programas informáticos específicos;
    %li Efetuar o tratamento de imagens, relativamente à sua cor e forma, utilizando programas informáticos específicos;
    %li Compor a estrutura das páginas, utilizando programas de informática específicos;
    %li Executar provas de baixa e alta resolução e heliográficas (ozalides), utilizando meios eletrónicos, a fim de verificar a sua conformidade com os objetivos pretendidos;
    %li Efetuar o registo da composição gráfica, em película e em chapa, com vista à sua posterior impressão, utilizando meios eletrónicos;
    %li Proceder à calibração dos equipamentos de forma a obter a qualidade pretendida na reprodução dos trabalhos gráficos;
    %li Efetuar o tratamento de textos e de imagens, compor e conceber as páginas para publicação “online” ou para apresentações “offline”.

app/views/courses/index.html.haml
/* Index */

.container-top.left
.container-middle.left

  / Content
  .content
    .content-box
      .content-item
        %h1 Sem Ridiculus Amet
        .separator.small
        .trix
          %div
            Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum id ligula porta felis euismod semper. Nullam id dolor id nibh ultricies vehicula ut id elit.

  .separator.medium

  / Courses
  .courses
    .courses-box
      .courses-item
        .courses-right
          .figure{ style: "background-image: url(#{image_path "course_thumbnail.png"})" }
        .courses-left
          %h3 Mollis Venenatis Pellentesque Inceptos
          .separator.small
          .trix.left
            %div Nulla vitae elit libero, a pharetra augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          = link_to "Ler Mais", course_path(id: "12345678"), class: "button large blue"

.container-bottom.left

app/views/courses/show.html.haml
/* Index */

.container-top.left
  .breadcrumbs
    .breadcrumbs-box
      .breadcrumbs-item
        = link_to courses_path, class: "link small" do
          .icon.left
            = image_tag "icons/back.png"
          voltar
.container-middle.left
  .content
    .content-box
      .content-item
        %h1.left Mollis Venenatis Pellentesque Inceptos
  .section-content
    .section-content-box
      .section-content-item
        .section-content-left
          .section-content-inner#ajax-content
            %h3 Risus Etiam Egestas
            .trix
              %div Nulla vitae elit libero, a pharetra augue. Vestibulum id ligula porta felis euismod semper. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.

              %div Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus.

              %div Curabitur blandit tempus porttitor. Nulla vitae elit libero, a pharetra augue. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Curabitur blandit tempus porttitor.
        .section-content-right
          .section-navigation
            .section-navigation-box
              .section-navigation-item
                = link_to "Risus Etiam Egestas", course_path(id: "12345678", title: "Risus Etiam Egestas"), remote: true, class: "button large blue"
              .section-navigation-item
                = link_to "Ridiculus Elit Fringilla Venenatis", course_path(id: "123456789", title: "Ridiculus Elit Fringilla Venenatis"), remote: true, class: "button large blue"
              .section-navigation-item
                = link_to "Cras Mollis", course_path(id: "1234567810", title: "Cras Mollis"), remote: true, class: "button large blue"
              .section-navigation-item
                = link_to "Dapibus Sem Mollis", course_path(id: "1234567811", title: "Dapibus Sem Mollis"), remote: true, class: "button large blue"

.container-bottom.left

app/views/courses/show.js.haml
:plain
  $("#ajax-content").html("#{j render("section")}");

app/views/default/index.html.haml
/* Index */

.container-top.left
.container-middle.left
  / Content
  .content
    .content-box
      .content-item
        %h1 Ridiculus Vestibulum Malesuada Sollicitudin Dapibus
        .separator.small
        .trix
          %div Donec id elit non mi porta gravida at eget metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Vestibulum id ligula porta felis euismod semper. Cras mattis consectetur purus sit amet fermentum.

          %div Aenean lacinia bibendum nulla sed consectetur. Curabitur blandit tempus porttitor. Donec id elit non mi porta gravida at eget metus. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Nullam quis risus eget urna mollis ornare vel eu leo. Donec id elit non mi porta gravida at eget metus.

          %div Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas sed diam eget risus varius blandit sit amet non magna. Donec id elit non mi porta gravida at eget metus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.

.container-bottom.left

app/views/home/index.html.haml
/* Index */

/
  .container-top.left
    .breadcrumbs
      .breadcrumbs-box
        .breadcrumbs-item
          = link_to root_path, class: "link small" do
            .icon.left
              = image_tag "icons/back.png"
            voltar

  .container-middle.left
    %h1 home #{application_configuration["environment"]}
    .separator.small
    %p Donec id elit non mi porta gravida at eget metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Vestibulum id ligula porta felis euismod semper. Cras mattis consectetur purus sit amet fermentum.

    %p Aenean lacinia bibendum nulla sed consectetur. Curabitur blandit tempus porttitor. Donec id elit non mi porta gravida at eget metus. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Nullam quis risus eget urna mollis ornare vel eu leo. Donec id elit non mi porta gravida at eget metus.

    %p Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas sed diam eget risus varius blandit sit amet non magna. Donec id elit non mi porta gravida at eget metus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.

  .container-bottom.left

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %meta{ content: "width=device-width, initial-scale=1.0", name: "viewport" }/
    %meta{ content: "IE=Edge", "http-equiv" => "X-UA-Compatible" }/
    %title= application_configuration["title"]
    %meta{ content: application_configuration["description"].to_s, name: "description" }/
    = render partial: "lib/global/meta_tags"
    = render partial: "lib/global/favicon"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
  %body
    = render partial: "lib/global/header"
    = render partial: "lib/global/responsive_navigation"
    = render partial: "lib/global/main"
    = render partial: "lib/global/footer"

app/views/layouts/application_landing.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %meta{ content: "width=device-width, initial-scale=1.0", name: "viewport" }/
    %meta{ content: "IE=Edge", "http-equiv" => "X-UA-Compatible" }/
    %title= application_configuration["title"]
    %meta{ content: application_configuration["description"].to_s, name: "description" }/
    = render partial: "lib/global/meta_tags"
    = render partial: "lib/global/favicon"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
  %body
    = render partial: "lib/global/header"
    = render partial: "lib/global/responsive_navigation"
    = render partial: "lib/global/billboard"
    // = render partial: "lib/global/main"
    = render partial: "lib/global/footer"

app/views/lib/components/_brand.html.haml
/* Brand header */

.brand
  .brand-box
    .brand-item
      = link_to root_path do
        = image_tag "brand.png", size: "128x32", class: "altai-center"

app/views/lib/components/_brand_footer.html.haml
/* Brand footer */

.brand-footer.right
  .brand-footer-box.right.altai-center
    .brand-footer-item.right
      = link_to root_path do
        = image_tag "brand.png", size: "128x32", class: "right"

app/views/lib/components/_brand_header.html.haml
/* Brand header */

.brand.left.altai-center
  .brand-box
    .brand-item
      = link_to root_path do
        = image_tag "brand.png", size: "128x32"

app/views/lib/components/_copyright.html.haml
/* Copyright */

.copyright.altai-center
  .copyright-box
    .copyright-item
      %p.extra-small.text-right
        Copyright © #{Time.zone.now.year} #{application_configuration["title"]}

app/views/lib/components/_group_navigation.html.haml
/* Group navigation */

.group-navigation.right
  .group-navigation-box
    .group-navigation-item
      = link_to root_path, class: "altai-center" do
        = image_tag "group_member.png", size: "256x64"
    .group-navigation-item
      = link_to root_path, class: "altai-center" do
        = image_tag "group_member.png", size: "256x64"

app/views/lib/components/_legal_navigation.html.haml
/* Legal navigation */

.legal-navigation.altai-center
  .legal-navigation-box
    .legal-navigation-item
      = link_to "Termos & Condições", root_path, class: "white"

app/views/lib/components/_primary_navigation_left.html.haml
/* Primary navigation */

.primary-navigation
  .primary-navigation-box.right
    .primary-navigation-item
      = link_to "menu", root_path, class: "altai-go-to altai-toggle-trigger "
    .primary-navigation-item
      = link_to "cursos", courses_path

app/views/lib/components/_primary_navigation_right.html.haml
/* Primary navigation */

.primary-navigation
  .primary-navigation-box.left
    .primary-navigation-item
      = link_to "notícias", root_path
    .primary-navigation-item
      = link_to "newsletter", root_path

app/views/lib/components/_responsive_navigation_trigger.html.haml
/* Responsive navigation trigger */

.responsive-navigation-trigger
  .responsive-navigation-trigger-box.right
    .responsive-navigation-trigger-item
      = link_to "menu", root_path, class: "altai-toggle-trigger"

app/views/lib/components/_secondary_navigation.html.haml
/* Secondary navigation */

.secondary-navigation
  .secondary-navigation-box
    .secondary-navigation-item
      = link_to "Default", default_index_path, class: "white"
    .secondary-navigation-item
      = link_to "Cursos", courses_path, class: "white"
    /
      .secondary-navigation-item
        = link_to "Instalações & Equipamento", root_path, class: "white"
      .secondary-navigation-item
        = link_to "Qualidade", root_path, class: "white"
      .secondary-navigation-item
        = link_to "Parcerias", root_path, class: "white"
      .secondary-navigation-item
        = link_to "Alunos", root_path, class: "white"
      .secondary-navigation-item
        = link_to "Pais", root_path, class: "white"
      .secondary-navigation-item
        = link_to "Professores", root_path, class: "white"
      .secondary-navigation-item
        = link_to "Notícias", root_path, class: "white"
      .secondary-navigation-item
        = link_to "Contactos", root_path, class: "white"
      .secondary-navigation-item
        = link_to "Newsletter", root_path, class: "white"

app/views/lib/components/_social_navigation.html.haml
/* Social navigation */

.social-navigation
  .social-navigation-box.altai-center
    .social-navigation-item
      = link_to root_path, class: "link large" do
        .icon.left
          = image_tag "icons/social_network.png", size: "32x32"
    .social-navigation-item
      = link_to root_path, class: "link large" do
        .icon.left
          = image_tag "icons/social_network.png", size: "32x32"
    .social-navigation-item
      = link_to root_path, class: "link large" do
        .icon.left.mg-0
          = image_tag "icons/social_network.png", size: "32x32"

app/views/lib/components/_sponsor_navigation.html.haml
/* Sponsor navigation */

.sponsor-navigation.right.altai-center
  .sponsor-navigation-box
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"
    .sponsor-navigation-item
      = link_to root_path do
        = image_tag "small_sponsor.png", size: "64x32"

app/views/lib/components/_vcard.html.haml
/* Vcard */

.vcard.right
  .vcard-box
    .vcard-item
      %p.small Address line one
      %p.small Address line two
      %p.small Postcode | City
      %p.small Country
      %p.small Email
      %p.small Telephone

app/views/lib/global/_billboard.html.haml
/* Billboard */

.universal.hero
  .billboard{ style: "background-image: url(#{image_path "billboard.png"})" }
    .billboard-box
      .billboard-item
        .separator.medium
        %h1 Uma escolha, um futuro.
        %p Donec id elit non mi porta gravida at eget metus. Aenean lacinia bibendum nulla sed consectetur.

app/views/lib/global/_favicon.html.haml
/* Favicon */

= favicon_link_tag "favicon/favicon-16x16.png", rel: "shortcut icon", type: "image/png", sizes: "16x16"
= favicon_link_tag "favicon/favicon-32x32.png", rel: "shortcut icon", type: "image/png", sizes: "32x32"
= favicon_link_tag "favicon/favicon-96x96.png", rel: "shortcut icon", type: "image/png", sizes: "96x96"
= favicon_link_tag "favicon/favicon-128x128.png", rel: "shortcut icon", type: "image/png", sizes: "128x128"
= favicon_link_tag "favicon/favicon-196x196.png", rel: "shortcut icon", type: "image/png", sizes: "196x196"
= favicon_link_tag "favicon/favicon.ico", rel: "shortcut icon", type: "image/x-icon", sizes: "64x64"

/* Apple */

= favicon_link_tag "favicon/apple-touch-icon-57x57.png", rel: "apple-touch-icon-precomposed", sizes: "57x57"
= favicon_link_tag "favicon/apple-touch-icon-60x60.png", rel: "apple-touch-icon-precomposed", sizes: "60x60"
= favicon_link_tag "favicon/apple-touch-icon-72x72.png", rel: "apple-touch-icon-precomposed", sizes: "72x72"
= favicon_link_tag "favicon/apple-touch-icon-76x76.png", rel: "apple-touch-icon-precomposed", sizes: "76x76"
= favicon_link_tag "favicon/apple-touch-icon-114x114.png", rel: "apple-touch-icon-precomposed", sizes: "114x144"
= favicon_link_tag "favicon/apple-touch-icon-120x120.png", rel: "apple-touch-icon-precomposed", sizes: "120x120"
= favicon_link_tag "favicon/apple-touch-icon-144x144.png", rel: "apple-touch-icon-precomposed", sizes: "144x144"
= favicon_link_tag "favicon/apple-touch-icon-152x152.png", rel: "apple-touch-icon-precomposed", sizes: "152x152"

/* Microsoft */

%meta{ content: application_configuration["title"].to_s, name: "application-name" }/
%meta{ content: "#FFFFFF", name: "msapplication-TileColor" }/
%meta{ content: image_url("favicon/mstile-144x144.png"), name: "msapplication-TileImage" }/
%meta{ content: image_url("favicon/mstile-70x70.png"), name: "msapplication-square70x70logo" }/
%meta{ content: image_url("favicon/mstile-150x150.png"), name: "msapplication-square150x150logo" }/
%meta{ content: image_url("favicon/mstile-310x150.png"), name: "msapplication-wide310x150logo" }/
%meta{ content: image_url("favicon/mstile-310x310.png"), name: "msapplication-square310x310logo" }/

app/views/lib/global/_footer.html.haml
/* Footer */

%footer.universal.footer
  .separator.large
  .universal-box
    .universal-item
      .footer-left
        = render partial: "lib/components/secondary_navigation"
      .footer-right
        = render partial: "lib/components/social_navigation"
        .separator.extra-small
        = render partial: "lib/components/brand_footer"
        .separator.extra-small
        = render partial: "lib/components/vcard"
        .separator.extra-small
        = render partial: "lib/components/group_navigation"
  .separator.large
  .wide.left
    .separator.extra-small
    = render partial: "lib/components/sponsor_navigation"
  .wide.left
    = render partial: "lib/components/legal_navigation"
  .wide.left
    = render partial: "lib/components/copyright"
    .separator.extra-small

app/views/lib/global/_header.html.haml
/* Header */

%header.universal.header
  .universal-box
    .universal-item
      = render partial: "lib/components/responsive_navigation_trigger"
      = render partial: "lib/components/primary_navigation_left"
      = render partial: "lib/components/brand"
      = render partial: "lib/components/primary_navigation_right"

app/views/lib/global/_main.html.haml
/* Main */

%main.universal.main.altai-panel
  .universal-box
    .universal-item
      = yield

app/views/lib/global/_meta_tags.html.haml
/* Open graph */

%meta{ content: application_configuration["title"].to_s, property: "og:title" }/
%meta{ content: application_configuration["description"].to_s, property: "og:description" }/
%meta{ content: "website", property: "og:type" }/
%meta{ content: application_configuration["url"].to_s, property: "og:url" }/
%meta{ content: image_url("opengraph/opengraph_default.png"), property: "og:image" }/

/* Twitter cards */

%meta{ content: "summary_large_image", name: "twitter:card" }/
%meta{ content: application_configuration["twitter_username"].to_s, name: "twitter:site" }/
%meta{ content: application_configuration["twitter_username"].to_s, name: "twitter:creator" }/
%meta{ content: application_configuration["title"].to_s, name: "twitter:title" }/
%meta{ content: application_configuration["description"].to_s, name: "twitter:description" }/
%meta{ content: image_url("opengraph/opengraph_default.png"), name: "twitter:image" }/

app/views/lib/global/_responsive_navigation.html.haml
/* Responsive navigation */

.universal
  .responsive-navigation.altai-toggle
    .responsive-navigation-box
      .responsive-navigation-column
        .responsive-navigation-item
          = link_to "Default", default_index_path, class: "blue altai-go-to"
        /
          .responsive-navigation-item
            = link_to "Instalações & Equipamento", root_path, class: "blue"
          .responsive-navigation-item
            = link_to "Qualidade", root_path, class: "blue"
          .responsive-navigation-item
            = link_to "Parcerias", root_path, class: "blue"
      .responsive-navigation-column
        .responsive-navigation-item
          = link_to "Cursos", courses_path, class: "blue"
        /
          .responsive-navigation-item
            = link_to "Notícias", root_path, class: "blue"
          .responsive-navigation-item
            = link_to "Contactos", root_path, class: "blue"
          .responsive-navigation-item
            = link_to "Newsletter", root_path, class: "blue"
    /
      .responsive-navigation-column
        .responsive-navigation-item
          = link_to "Alunos", root_path, class: "blue"
        .responsive-navigation-item
          = link_to "Pais", root_path, class: "blue"
        .responsive-navigation-item
          = link_to "Professores", root_path, class: "blue"